const DataTypes = require('../DataTypes');

class AbstractAssociation {

  constructor(source, target, options) {
    if (this.constructor === AbstractAssociation) {
      throw new Error('This Class should not be instantiated, please extend');
    }
    this.source = source;
    this.target = target;
    this.options = {
      ...options
    }
  }

  _addForeignKeyConstraints() {
    throw new Error('_addForeignKeyConstraints must be implemented');
  }

  /**
   * Adds an foreign reference to the table of modelReferencing, referencing the table of modelBeingReferenced
   * @param {*} modelBeingReferenced
   * @param {*} modelReferencing
   */
  _addReferenceID(modelBeingReferenced, modelReferencing){
    let referenceAttribute = {};
    let referenceAttributeName = `${modelBeingReferenced.name}_id`;
    referenceAttribute[referenceAttributeName] = {
      type: DataTypes.INT,
      notNull: true,
      autoIncrement: true,
      _autoGenerated: true,
      references: {
        table: modelBeingReferenced.name,
        column: 'id'
      }
    }
    modelReferencing.rawAttributes = {
      ...modelReferencing.rawAttributes,
      ...referenceAttribute
    }

    // Add getter & setter for foreign reference
    Object.defineProperty(modelReferencing.prototype, referenceAttributeName, {
      get: function() {
        return this.get(referenceAttributeName);
      },
      set: function() {
        this.set(referenceAttributeName);
      }
    })

    modelReferencing.refreshAttributes();
  }
}

module.exports = AbstractAssociation;