language: node_js
node_js:
  - '9'

sudo: required

# Cache npm inbetween builds to improve build time
# Documentaion - https://docs.travis-ci.com/user/caching/
cache:
  yarn: true
  directories:
  - node_modules # NPM packages

# registering to user postgresql database
services:
 - postgresql

#creates the database
before_install:
 - psql -c 'create database pwadb;' -U postgres --set AUTOCOMMIT=off

# Deploy
# Bluemix
deploy:
  - provider: cloudfoundry
    username: ${IBM_CLOUD_USER}
    #########################
    ## Add BLUEMIX_PASSWORD environment variable to your Travis project's settings
    ## https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
    #########################
    password: ${IBM_CLOUD_PASSWORD}
    organization: ${IBM_CLOUD_USER}
    space: production
    region: eu-gb
    api: https://api.ng.bluemix.net/
    skip_cleanup: true
    on:
      branch: master
  - provider: cloudfoundry
    username: ${IBM_CLOUD_USER}
    #########################
    ## Add BLUEMIX_PASSWORD environment variable to your Travis project's settings
    ## https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
    #########################
    password: ${IBM_CLOUD_PASSWORD}
    organization: ${IBM_CLOUD_USER}
    space: staging
    region: eu-gb
    api: https://api.ng.bluemix.net/
    skip_cleanup: true
    on:
      branch: staging